__лабораторная работа N1:__  средства языка Python для работы с данными

__часть 2:__ библиотека numpy, базовые методы линейной алгебры

__цель:__ изучить возможности библиотеки numpy

__порядок выполнения:__ выполните задания представленные ниже

__литература__

- Абдрахманов М.И., Мамонов И.А.  Линейная алгебра на Python. - devpractice.ru. 2019.

- Криволапов С.Я., Хрипунова М.Б.    Математика на Python. - КноРус. 2022

----

# Импортируйте пакет numpy под именем np

 

In [1]:
import numpy as np

# Распечатайте версию numpy

In [2]:
np.__version__

'2.5.1'

# Создайте вектор из нулей размером 10

 

In [3]:
arr = np.zeros(10, dtype=int)

print(arr)

[0 0 0 0 0 0 0 0 0 0]


# Как определить объем занимаемой масивом памяти 

 

In [4]:
print(arr.nbytes)
# с помощью метода nbytes

80


# Как получить справку по функции add

In [5]:
help(np.add)
# или
# np.add.__doc__

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

# Создайте нулевой вектор размером 10, но с пятым значением, равным 1

In [6]:
arr = np.zeros(10, dtype=int)
arr[4] = 1

print(arr)

[0 0 0 0 1 0 0 0 0 0]


# Создайте вектор со значениями от 10 до 49

In [7]:
arr = np.arange(10, 50)

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# "Переверните" вектор (первый элемент станет последним)

 

In [8]:
arr = np.flip(arr)

print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# Создайте матрицу 3х3 со значениями от 0 до 8

 

In [9]:
arr = np.arange(0, 9)
arr = arr.reshape((3, 3))

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Найдите индексы ненулевых элементов из [1,2,0,0,4,0]

 

In [10]:
arr = np.array([1, 2, 0, 0, 4, 0])
idx = np.nonzero(arr)[0]

print(idx)

[0 1 4]


# Создайте единичную матрицу 3х3

 

In [11]:
arr = np.eye(3, 3, dtype=int)

print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Создайте массив 3х3х3 со случайными значениями

 

In [12]:
arr = np.random.randint(0, 10, size=(3, 3, 3))

print(arr)

[[[6 3 3]
  [2 1 0]
  [4 5 2]]

 [[6 3 0]
  [7 0 3]
  [1 8 1]]

 [[5 3 4]
  [7 6 8]
  [3 8 5]]]


# Создайте массив 10х10 со случайными значениями и найдите минимальное и максимальное значения

In [13]:
arr = np.random.randint(-100000, 100000, size=(10, 10))

print(f"min: {np.min(arr)}")
print(f"max: {np.max(arr)}")

min: -98327
max: 96975


# Создайте случайный вектор размером 30 и найдите среднее значение
 

In [14]:
arr = np.random.randint(-99, 99, size=30)

print(f"M(X): {np.mean(arr)}")

M(X): 15.0


# Создайте двумерный массив с 1 на границе и 0 внутри

In [15]:
arr = np.ones((5, 5), dtype=int)
arr[1:-1, 1:-1] = 0

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Как добавить границу (заполненную нулями) вокруг существующего массива?

In [16]:
# с помощью функции pad

arr = np.random.randint(1, 100, size=(5, 5))
print("Исходный массив:")
print(arr)

arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\nС границей из нулей:")
print(arr)

Исходный массив:
[[20 18 81 48 93]
 [35 93 70 17 48]
 [67 18 94 39 70]
 [64 19  1 80 39]
 [79 73 28  7 62]]

С границей из нулей:
[[ 0  0  0  0  0  0  0]
 [ 0 20 18 81 48 93  0]
 [ 0 35 93 70 17 48  0]
 [ 0 67 18 94 39 70  0]
 [ 0 64 19  1 80 39  0]
 [ 0 79 73 28  7 62  0]
 [ 0  0  0  0  0  0  0]]


# Создайте матрицу размером 5х5 со значениями 1,2,3,4 чуть ниже главной диагонали

In [17]:
arr = np.diag(np.arange(1,5), k=-1)

print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# Извлеките целую часть из случайного массива чисел

In [18]:
arr = np.random.uniform(-10, 10, size=30)
print("Исходный массив")
print(arr)

arr = np.trunc(arr)
print("\nОкруглённый массив")
print(arr)

Исходный массив
[-1.94731861  2.50060025 -1.95747482  5.88530315 -7.21207118  2.16670524
 -5.17673902  6.41299136  0.76595175  0.0717632  -4.59665619  6.9743242
  2.27478087  1.87101214 -7.61303985 -8.77879521  2.05607745 -8.91207595
 -2.75090606 -2.13893951  7.87666821 -1.26603009  7.16885587  0.28157147
 -0.45124651 -1.81895538  8.82575363  1.1465348  -6.32015238  0.77281976]

Округлённый массив
[-1.  2. -1.  5. -7.  2. -5.  6.  0.  0. -4.  6.  2.  1. -7. -8.  2. -8.
 -2. -2.  7. -1.  7.  0. -0. -1.  8.  1. -6.  0.]


# Создайте матрицу размером 5х5 со значениями в строках от 0 до 4

In [19]:
matrix = np.tile(np.arange(5), (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# Создайте случайный вектор размером 10 и отсортируйте его

 

In [20]:
arr = np.random.randint(-500, 500, size=10)
print("Исходный массив")
print(arr)

arr.sort()
print("\nОтсортированный массив")
print(arr)

Исходный массив
[-414 -238   27 -142  385 -321 -292 -401 -137  436]

Отсортированный массив
[-414 -401 -321 -292 -238 -142 -137   27  385  436]


# Сгенерируйте два случайных массива A и B, проверьте их на равенство

 

In [21]:
a = np.random.randint(-25, 25, size=10)
b = np.random.randint(-25, 25, size=10)

print("A:", a)
print("B:", b)

print("\nПоэлементно")
print(a == b)

print("\nРавенство массивов")
print(np.array_equal(a, b))

A: [  8  -3  -9 -13  15   9  12  -6  13 -25]
B: [ 18  12 -25  -7  -8 -23   8 -22  -7  19]

Поэлементно
[False False False False False False False False False False]

Равенство массивов
False


# Сгенерируйте случайную матрицу размером 10х2, представляющую декартовы координаты, преобразуйте их в полярные координаты

 

In [22]:
dec = np.random.uniform(-10, 10, size=(10, 2))

x = dec[:, 0]
y = dec[:, 1]

print("Декартовы координаты (x, y):")
print(dec)

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar = np.column_stack((r, theta))

print("\nПолярные координаты (r, theta в радианах):")
print(polar)

Декартовы координаты (x, y):
[[ 7.72867356  4.97051603]
 [-0.22785837  1.17885679]
 [-5.36971667  7.24133569]
 [-0.88598395  3.97079752]
 [-9.57030131 -7.26768867]
 [-2.44103308  0.69663538]
 [-1.27827514  9.50999418]
 [-9.82480981  2.11411848]
 [-4.91643927  3.3403382 ]
 [ 5.82572577  4.12450779]]

Полярные координаты (r, theta в радианах):
[[ 9.18903828  0.57152816]
 [ 1.20067596  1.76172938]
 [ 9.01503188  2.20885893]
 [ 4.06843957  1.79032534]
 [12.01706977 -2.49210252]
 [ 2.53849234  2.86359702]
 [ 9.59551857  1.70440937]
 [10.04969575  2.92964291]
 [ 5.94384004  2.54481118]
 [ 7.13797207  0.61606281]]


# Для двух случайных массивов X и Y постройте матрицу C 
$C_{ij} = \frac{1}{x_i - y_j}$

In [23]:
x = np.random.rand(4)
y = np.random.rand(4)

print("X:", x)
print("Y:", y)
print()

c = 1 / (x[:, None] - y[None, :])

print(c)

X: [0.476007   0.36732457 0.08923176 0.08941677]
Y: [0.92670182 0.99940031 0.4557515  0.93649349]

[[ -2.2187963   -1.91060908  49.3693074   -2.1716164 ]
 [ -1.78770229  -1.58208888 -11.30877134  -1.75694766]
 [ -1.19407253  -1.0986976   -2.72836597  -1.18027283]
 [ -1.19433639  -1.09892098  -2.72974391  -1.18053062]]


# Сгенерируйте две случайные матрицы A и B, перемножьте их

In [24]:
a = np.random.randint(1, 10, size=(5, 5))
b = np.random.randint(1, 10, size=(5, 5))

print("A:\n", a)
print("B:\n", b)
print()

result = a @ b

print(result)

A:
 [[6 5 1 3 8]
 [8 7 4 4 9]
 [9 4 4 4 9]
 [9 3 7 5 3]
 [3 5 6 9 8]]
B:
 [[6 3 6 4 8]
 [7 7 2 4 9]
 [4 3 8 2 1]
 [7 3 6 8 6]
 [2 2 1 9 8]]

[[112  81  80 142 176]
 [159 115 127 181 227]
 [144  97 127 173 208]
 [144  90 149 129 160]
 [156 105 138 188 193]]


# Сгенерируйте вектор a и матрицу B, перемножте их

In [25]:
a = np.random.randint(-10, 10, size=4)
b = np.random.randint(-10, 10, size=(4, 4))

print("A:", a)
print("B:\n", b)
print()

result = np.multiply(a, b)

print(result)

A: [9 5 8 1]
B:
 [[  3  -2  -4 -10]
 [  5  -8   1  -6]
 [ -9   8 -10  -3]
 [  4  -3   2  -2]]

[[ 27 -10 -32 -10]
 [ 45 -40   8  -6]
 [-81  40 -80  -3]
 [ 36 -15  16  -2]]
